import Providers from "@/lib/Providers/Providers";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  // display: "swap",
  variable: "--font-montserrat", // Define CSS variable
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  // display: "swap",
  variable: "--font-inter", // Define CSS variable
});

export const metadata: Metadata = {
  title: "Blood Donation",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${inter.variable} antialiased`}>
        <Providers>{children}</Providers>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
};

export default RootLayout;
