export const bloodGroups = [
  "A_POSITIVE",
  "A_NEGATIVE",
  "B_POSITIVE",
  "B_NEGATIVE",
  "AB_POSITIVE",
  "AB_NEGATIVE",
  "O_POSITIVE",
  "O_NEGATIVE",
];

export const cities = [
  "Dhaka",
  "Chittagong",
  "Khulna",
  "Rajshahi",
  "Sylhet",
  "Barisal",
  "Rangpur",
  "Mymensingh",
  "Comilla",
  "Gazipur",
  "Narayanganj",
  "Bogura",
  "Kushtia",
  "Jessore",
  "Nawabganj",
  "Pabna",
  "Dinajpur",
  "Faridpur",
  "Saidpur",
  "Tangail",
  "Jamalpur",
  "Netrakona",
  "Sirajganj",
  "Brahmanbaria",
  "Panchagarh",
  "Bhola",
  "Shariatpur",
  "Lakshmipur",
  "Munshiganj",
  "Manikganj",
  "Meherpur",
  "Chuadanga",
  "Magura",
  "Jhalokathi",
  "Pirojpur",
  "Narail",
  "Lalmonirhat",
  "Kurigram",
  "Thakurgaon",
  "Nilphamari",
  "Gaibandha",
  "Sherpur",
  "Habiganj",
  "Maulvibazar",
  "Sunamganj",
  "Kishoreganj",
  "Feni",
  "Noakhali",
  "Bagerhat",
  "Bandarban",
  "Cox's Bazar",
  "Khagrachhari",
  "Rangamati",
];

export const availability = ["Yes", "No"];

export const bloodBagNumbers = ["1", "2", "3", "4", "5"];
