export const Status = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  BLOCKED: "BLOCKED",
  UNBLOCKED: "UNBLOCKED",
  DELETED: "DELETED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCEL: "CANCEL",
  SUCCESSFUL: "SUCCESSFUL",
};

export const Gender = ["MALE", "FEMALE"];
